### ISSUE TITLE
Implement Continuous Integration and deployment

### ISSUE THREAD

**Issue by Gadgetoid** [rpi-ws281x/rpi-ws281x-python#62]
This library- due to infrequent updates keeping it off my radar most of the time- has slipped through the cracks of best practise and is missing some CI and deployment workflows that could help externalise some of the steps I (having half forgotten) perform when a new release is required.

Releases are so infrequent that this might not be worth the hassle, but maybe we should:

* [ ] Implement GItHub workflow to build library and check it compiles
* [ ] Implement GitHub workflow to deploy tagged releases to PyPi (Potentially?)

**Comment by cp2004** [comment]
This may be of use for the pushing to PyPi:
https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

I looked at this, I think something like this would work. Building universal wheels in this lib *I don't think* will work on GH actions so the build on push is not much use since it is only sdist. Piwheels should do it for RPi anyway, so just sdist should be good enough for users.

```yaml
name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on:
  push:
  release:
    types: [released]
jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Build a source tarball
      run: |
        cd library
        python setup.py sdist

     - name: Publish distribution 📦 to Test PyPI
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution 📦 to PyPI
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
```
@Gadgetoid Let me know what you think, maybe publishing 4.2.6 can be it's test run... though it may be better to test this exclusively on TestPyPi first. I may be able to make a PR to do this, I'll see how it goes.
